#registry:
#  image: registry:2.0.1
#  ports:
#    - "5000:5000"
#    - "5001:5001"
#  environment:
#    SETTINGS_FLAVOR: s3
#    AWS_BUCKET: modern_web
#    STORAGE_PATH: /registry
#    AWS_KEY: AKIAIZR3NY62HLMIFPTA
#    AWS_SECRET: 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
#    SEARCH_BACKEND: sqlalchemy
graphite:
  restart: always
  image: hopsoft/graphite-statsd
  ports:
    - "80:80"
    - "2003:2003"
    - "8125:8125/udp"
app:
  build: .
  ports:
   - "8080:8080"
  environment:
    MIX_ENV: prod
    PORT: 8080
  links:
    - db
    - graphite
db:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: modern_web_prod
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: PgSQL@2015!!

