
app:
  build: .
  ports:
   - "8080:8080"
  environment:
    MIX_ENV: prod
    PORT: 8080
  links:
    - db
db:
  restart: always
  image: postgres:latest
  ports:
    - "5432"
  environment:
    POSTGRES_DB: modern_web_prod
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: PgSQL@2015!!

