use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :modern_web, ModernWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "example.com"],
  cache_static_manifest: "priv/static/manifest.json"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section:
#
#  config :modern_web, ModernWeb.Endpoint,
#    ...
#    https: [port: 443,
#            keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#            certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables point to a file on
# disk for the key and cert.

# Do not print debug messages in production
config :logger, level: :info

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :modern_web, ModernWeb.Endpoint, server: true
#

# Monitoring Configuration
#import_config "prod.statsd.exs"
config :ex_statsd,
       host: "graphite",
       port: 8125,
       namespace: "modern_web"

# Crypto Configuration
config :comeonin,
  crypto_mod: :pbkdf2,
  bcrypt_log_rounds: 14,
  pbkdf2_rounds: 100_000,
  pass_length: 16,
  pass_min_length: 12

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"


